"""Hand-written Phase 4 scenario gate.

Anti-auto-referential corpus — scenarios encode observations that were
NOT generated by _simulate_failure. Each scenario declares a
ground_truth_match (kind + role [+ expected_mode]); the test asserts
that at least one hypothesis matching the criteria lands in the top-N.

If the named device_slug / observation target isn't present in the
compiled graph (e.g. fresh checkout, different board), the scenario
is SKIPPED with a warning, not failed.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from api.pipeline.schematic.hypothesize import Observations, hypothesize
from api.pipeline.schematic.schemas import ElectricalGraph

_FIXTURE = Path(__file__).parent / "fixtures" / "hand_written_scenarios.yaml"


def _load_graph(slug: str) -> ElectricalGraph | None:
    path = Path("memory") / slug / "electrical_graph.json"
    if not path.exists():
        return None
    return ElectricalGraph.model_validate_json(path.read_text())


def _scenarios():
    data = yaml.safe_load(_FIXTURE.read_text())
    return data.get("scenarios", [])


@pytest.mark.parametrize("scenario", _scenarios(), ids=lambda s: s["id"])
def test_hand_written_scenario_has_matching_top_n(scenario):
    graph = _load_graph(scenario["device_slug"])
    if graph is None:
        pytest.skip(f"graph missing for {scenario['device_slug']}")

    obs = Observations(
        state_comps=scenario["observations"].get("state_comps", {}),
        state_rails=scenario["observations"].get("state_rails", {}),
    )

    # Pre-check: every observation target must exist in the graph.
    missing = [
        t for t in list(obs.state_comps) + list(obs.state_rails)
        if t not in graph.components and t not in graph.power_rails
    ]
    if missing:
        pytest.skip(f"graph missing targets: {missing}")

    # Pre-check: a matching passive must exist in the compiled graph.
    match = scenario["ground_truth_match"]
    candidates = [
        r for r, c in graph.components.items()
        if getattr(c, "kind", "ic") == match["kind"]
        and getattr(c, "role", None) == match["role"]
    ]
    if not candidates:
        pytest.skip(
            f"no passive matches kind={match['kind']} role={match['role']} "
            f"in {scenario['device_slug']} graph"
        )

    result = hypothesize(graph, observations=obs, max_results=scenario["accept_in_top_n"])
    hits = [
        h for h in result.hypotheses
        if len(h.kill_refdes) == 1
        and h.kill_refdes[0] in candidates
        and h.kill_modes[0] == match["expected_mode"]
    ]
    assert hits, (
        f"scenario {scenario['id']}: no matching hypothesis in top "
        f"{scenario['accept_in_top_n']}. Top hypotheses: "
        f"{[(h.kill_refdes, h.kill_modes, h.score) for h in result.hypotheses[:5]]}"
    )
